// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvB4p_0WnApZJohe7XVm38NZDkBt8ec0',
    appId: '1:642232760815:web:4ef7c5886e374c95d25e1a',
    messagingSenderId: '642232760815',
    projectId: 'xx-quiz',
    authDomain: 'xx-quiz.firebaseapp.com',
    storageBucket: 'xx-quiz.appspot.com',
    measurementId: 'G-M2KPCVX5V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EtC0fVxdVtHV7LKjw439fLfWBiCgmj0',
    appId: '1:642232760815:android:a64c324843c8af49d25e1a',
    messagingSenderId: '642232760815',
    projectId: 'xx-quiz',
    storageBucket: 'xx-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtMd1pk5KVd3BHY6k22tU8txst6mbd9Lw',
    appId: '1:642232760815:ios:b3105358b5e44393d25e1a',
    messagingSenderId: '642232760815',
    projectId: 'xx-quiz',
    storageBucket: 'xx-quiz.appspot.com',
    iosClientId: '642232760815-ehbu2r4tg28ag952f260nl1aej2m0v0c.apps.googleusercontent.com',
    iosBundleId: 'com.example.QuizApp',
  );
}
